### ISSUE TITLE
Player tips are intentionally "translated" wrong

### ISSUE THREAD

**Issue by tommyahugo** [PolCPP/PSO2es-Translation#180]
Most of player tips during loading screen is intentionally "translated" wrong, which they are either simply troll, offense or irrelevent, and they get worse every update. Maybe because I download the "troll patch" instead of "translation patch" but it from the es tweaker.

**Comment by SynthSy** [comment]
Welcome!
If you see an offending line, please edit/translate them and submit a pull request.
Needs to be in proper J however.

**Comment by tommyahugo** [comment]
Seriously please, I mean no offense at all.

Sorry, I'm no translator, I just try to report the issue I spot. Maybe the patch is always like this from day 1 but I just play es not long ago so I don't know anything about this. There for please forgive me if this is the case here, just ignore whatever I type below and close the issue.

Well, at least I can point out all the line that is translated wrong though, so please take a look at them, they are in UIQuestTipsText.

- 0007: Tip about friend assist become anitwitter
- 0011: Tip about quest area become figurines
- 0027: Tip about special quest that give matterial become chinese cartoon and rule 34.
- 0044: Tip about Darker Weakness become d**k outside skirt (seriously, this keep showing up in my game recently, that why I snap and go report here).
- 0045: Tip about rare drop become Re:Zero anime with the best girl called Emilia.
- 0052: Tip about costume become a whining that PSO2 is a terrible game.
- 0093: Tip about darker wave (I think?) become githud.
- 0097: Tip about friend become recruiting for translation (and yeah, I do think what I'm doing right now is one way to contribute to this project) (btw this tip is not showing up recently though).
- 0098: Seem like a tip about rare drop in quest which become comment about Boku No Pico anime.
- 0106: Tip about Fighter class become a sarcasm that player character is not "sugoi" (as i understand it is すごい means great or amazing, maybe wrong).
- 0107: Tip about Gunner class become a sarcasm that player character is an accident.
- 0108: Tip about Techer class become  as sarcasm that player anime is s**t.
- 0109: DR.Cohen tip become another recruitment for translation (which also not show up recently)
- 0118: Same as above.
- 0133: Tip about strong enemy (boosted enemy?) become a sarcasm that if you are not running 6s affix you should uninstall the game (is it really matter in es?).
- 0135: Tip about reward for achievement become slide shaker.
- 0145: Another recruitment.
- 0149: Donovan (the cast with Dr.Cohen iirc) tip become a sarcasm that player character look like s**t.
- 0150: Recruitment.

Please don't misunderstanding, I didn't said that all the tips are wrong, it just those unrelevant tips keep showing up more and more. Really if I didn't come here to report I will never know that there are lots of tips that are translated right. I understand this translation is a hard job with no reward, but if this is the way to relieve your stress then it is simply wrong to me.

**Comment by SynthSy** [comment]
I just accept whatever pull request these days, too much time on my hands doing the chip descriptions.
Quest tips are lowest priority for me right now.

If they're wrong, then please by all means, fix them. If not, then it's unfortunate, but you'll have to live with them.

**Comment by tommyahugo** [comment]
Like I said, I'm no translator, so yeah I guess I will live with them, but I still hope that you will consider it sometimes. Please close the issue.

PS: I just check the lastest change in the file, it seem it a way to entertain between translators. Please do me a favor just keep it up here, not in the final product, thanks in advance.

**Comment by SynthSy** [comment]
When I get back to them after achieving my goals for the chips, I'll come back to them. Anything that isn't very helpful (even by JP translation) will be replaced with a translation help request.

For now, any jokes or comments in them will stay.
