### ISSUE TITLE
Receive item from mail does not pop up dialog of getting said item

### ISSUE THREAD

**Issue by alama** [PolCPP/PSO2es-Translation#66]
This allow the user to "try" again to get the item, but the server return an error,  I think 523?

**Comment by SynthSy** [comment]
That's something wrong with the game itself, not with the eng patch.

And it is our fault, we can't fix it.

**Comment by alama** [comment]
Odd, without the ENG patch, I get the normal "Got: # of item" dialog box, but with the EN patch, I do not get the dialog

**Comment by SynthSy** [comment]
Gonna need you to test something once I updated the UIText

**Comment by SynthSy** [comment]
Ok, compile the patch and manually add

**Comment by alama** [comment]
This is going to wait until 10 AM EST, when I get 2 mails with items on my chars to test out the new patch

**Comment by SynthSy** [comment]
That's fine.

**Comment by alama** [comment]
I was able to get an item from a mail (for collecting # of chip type), I think the issue had been fixed

**Comment by SynthSy** [comment]
Great!
