### ISSUE TITLE
ESBreaker does not work under wine 1.9.2

### ISSUE THREAD

**Issue by alama** [PolCPP/PSO2es-Translation#67]
![](http://i.imgur.com/iKOIioH.png)

**Comment by SynthSy** [comment]
If you could still click on the buttons, then left is "load it", middle is "load in and generate updated json" and right is "save changes"

As for fixing it, that is all Rupi's area of expertise. For now, could use a VM, or use my link [here](https://dl.dropboxusercontent.com/u/3260503/Patched_FileCo.dat)

**Comment by PolCPP** [comment]
Well it runs under unity which uses mono...so it shouldn't work under unity. Here a Linux build

https://dl.dropboxusercontent.com/u/3115520/LinuxEsBreaker.zip
