### ISSUE TITLE
Can not use "Product Search"

### ISSUE THREAD

**Issue by alama** [PolCPP/PSO2es-Translation#80]
*not my device*
OS: Android Lolipop 5.1.1
Model: Samsung Galaxy Tab S2
Model number: SM-T817V
PSO2es version: 2.1.1
Patch version: 57
 
Steps to reproduce:

1. Click the Rappy with the tilted head icon on the bottom right side of the screen., "PSO2 Functions" 
2. Click the second option, "My Shop"
3. Click the first option, "Product Search"
4. Try to press any button on the screen.

**Comment by alama** [comment]
I can reproduce this issue on my device as well, The OnePlus One, model A0001, Running Android 5.1.1

**Comment by kamijoutouma** [comment]
The device listed in the OP is mine and thx alama I finally was able to get in.

**Comment by SynthSy** [comment]
Yeah, I had this issue earlier, and I fixed it before i went to bed, will have the fix pushed out now, totally sorry.

**Comment by kamijoutouma** [comment]
Awesome thx

**Comment by SynthSy** [comment]
Yeah, the issue was some of the weapon camos and one of the affix abilities came up as "null."

This was relatively hard to find, since my phone (which uses an earlier patch) also had this issue. So patch 57 and Patch 56 had this issue. Anyways, I apologize for the inconvenience >.<

**Comment by alama** [comment]
Could it be so hard to ask for tagging which commit is to which patch release (for history tracking) and just have the commit that fixes this issue have a line that said "fixes #80" so GitHub will note which commit fixed said issue and close the ticket?

**Comment by SynthSy** [comment]
I try to, most part, but i use github's own software, which will mark ALL of the said stuff with the title.

This is an issue for myself, since I tend to lose track on what I've updated as I usually update while playing PSO2.
